FROM docker.dev.trigon.hu/docker/pgsql:11

ENV PGSQL_ROOT_USER=root
ENV PGSQL_ROOT_PASS=root
ENV PGSQL_DATABASE=root


# FROM postgres:11-alpine

# ENV POSTGRES_USER=root
# ENV POSTGRES_PASSWORD=root
# ENV POSTGRES_DB=root
